### ISSUE TITLE
kube-rbac-proxy address already in use

### ISSUE THREAD

**Issue by tomsherrod** [coreos/prometheus-operator#1612]
**What did you do?**
Quick start with kube-prometheus

**What did you expect to see?**
running pods in monitoring namespace
Grafana is fine and metrics from master is fine. Pulling values from prometheus dashboard works.

**What did you see instead? Under which circumstances?**
node-exporter-d7mxn                    1/2       CrashLoopBackOff   219        19h
node-exporter-jzvnw                    2/2       Running            0          19h
node-exporter-pwfh4                    1/2       CrashLoopBackOff   220        19h
node-exporter-vbgmt                    1/2       CrashLoopBackOff   220        19h

Logs:
F0712 18:16:20.314448   21329 main.go:197] Failed to listen on secure address: listen tcp :9100: bind: address already in use
On each of them.

**Environment**
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kubadm

Pointers?

Thanks,
Tom

**Comment by mxinden** [comment]
Node exporter is running is in host networking. Thereby it binds to a port (`9100`) directly on your nodes interfaces. Can you make sure no other application is already set to that port on your node?

You could:

1. ssh into a node
2. run `netstat -l`

Feel free to post the output here so we can further debug your issue.

**Comment by brancz** [comment]
I think this is because two node-exporter pods are attempting to bind to the same hostport. I seem to recall there is some undocumented feature for the daemonset that enforces that a pod _must_ be terminated before a new one is rolled out.

**Comment by brancz** [comment]
@tomsherrod could you try setting `terminationGracePeriodSeconds: 0` in the daemonset's pod template?

**Comment by tomsherrod** [comment]
@mxinden 
netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1236/sshd       
tcp        0      0 0.0.0.0:53848           0.0.0.0:*               LISTEN      18706/rpc.statd 
tcp        0      0 127.0.0.1:44325         0.0.0.0:*               LISTEN      23387/kubelet   
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      23387/kubelet   
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      23182/kube-proxy
tcp        0      0 127.0.0.1:9101          0.0.0.0:*               LISTEN      23983/node_exporter
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      18708/rpcbind   
tcp6       0      0 :::30326                :::*                    LISTEN      23182/kube-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1236/sshd       
tcp6       0      0 :::51035                :::*                    LISTEN      18706/rpc.statd 
tcp6       0      0 :::30016                :::*                    LISTEN      23182/kube-proxy
tcp6       0      0 :::31680                :::*                    LISTEN      23182/kube-proxy
tcp6       0      0 :::30535                :::*                    LISTEN      23182/kube-proxy
tcp6       0      0 :::10250                :::*                    LISTEN      23387/kubelet   
tcp6       0      0 :::32171                :::*                    LISTEN      23182/kube-proxy
tcp6       0      0 :::9100                 :::*                    LISTEN      1243/node_exporter
tcp6       0      0 :::111                  :::*                    LISTEN      18708/rpcbind   
tcp6       0      0 :::10255                :::*                    LISTEN      23387/kubelet   
tcp6       0      0 :::10256                :::*                    LISTEN      23182/kube-proxy
udp        0      0 127.0.0.1:650           0.0.0.0:*                           18706/rpc.statd 
udp        0      0 0.0.0.0:652             0.0.0.0:*                           18708/rpcbind   
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:43786           0.0.0.0:*                           18706/rpc.statd 
udp        0      0 0.0.0.0:111             0.0.0.0:*                           18708/rpcbind   
udp6       0      0 :::652                  :::*                                18708/rpcbind   
udp6       0      0 :::47746                :::*                                18706/rpc.statd 
udp6       0      0 :::111                  :::*                                18708/rpcbind   

docker ps | grep exporter
b70f30ce4b62        ff5ecdcfc4a2                                                                                                 "/bin/node_exporte..."   42 hours ago        Up 42 hours                             k8s_node-exporter_node-exporter-d7mxn_monitoring_82e8896a-855a-11e8-9e2d-005056bc3ce7_0
5eb711ee6f59        k8s.gcr.io/pause:3.1                                                                                         "/pause"                 42 hours ago        Up 42 hours                             k8s_POD_node-exporter-d7mxn_monitoring_82e8896a-855a-11e8-9e2d-005056bc3ce7_0

Within the working master node-exporter container:
tcp        0      0 127.0.0.1:9101          0.0.0.0:*               LISTEN      26537/node_exporter
tcp        0      0 :::9100                 :::*                    LISTEN      26595/kube-rbac-pro
A failing node node-exporter container:
tcp        0      0 127.0.0.1:9101          0.0.0.0:*               LISTEN      23983/node_exporter
tcp        0      0 :::9100                 :::*                    LISTEN      -

@brancz Will give it a try.

Thank you both!

**Comment by tomsherrod** [comment]
@brancz No joy. Even after the change, they fall back into the CrashLoopBackOff.

**Comment by Dissonant-Tech** [comment]
@tomsherrod Did you find any solution to this problem? I am currently experiencing it as well. The port is in use by node-exporter, and setting a termination grace period (whether to 0 or something like 60) does not work.

**Comment by tomsherrod** [comment]
@Dissonant-Tech I did not find a specific solution. I have installed it on a new cluster, actually a couple of other clusters without issue. I did find on one of the images being used, a host node_exporter set to start with machine startup. Why it was not showing up with netstat, not sure. I now make sure host images do NOT have node_exporter even installed.

**Comment by Liyankuan** [comment]
have a official solution？the same problem

**Comment by brancz** [comment]
Which version of Kubernetes are you on? This sounds like a problem that should have been fixed already according to https://github.com/kubernetes/kubernetes/issues/52973

**Comment by Dissonant-Tech** [comment]
I am currently on kuberentes 1.11.

@Liyankuan I solved the issue by making the following changes in my yaml:

```diff
diff --git a/deploy/monitoring/node-exporter-daemonset.yaml b/deploy/monitoring/node-exporter-daemonset.yaml                                                                                                       
index 6a2add1..b482a39 100644
--- a/deploy/monitoring/node-exporter-daemonset.yaml
+++ b/deploy/monitoring/node-exporter-daemonset.yaml
@@ -16,7 +16,7 @@ spec:
     spec:
       containers:
       - args:
-        - --web.listen-address=127.0.0.1:9100
+        - --web.listen-address=127.0.0.1:9101
         - --path.procfs=/host/proc
         - --path.sysfs=/host/sys
         - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
@@ -43,7 +43,7 @@ spec:
           readOnly: true
       - args:
         - --secure-listen-address=$(IP):9100
-        - --upstream=http://127.0.0.1:9100/
+        - --upstream=http://127.0.0.1:9101/
         env:
         - name: IP
           valueFrom:
```

basically just set the node-exporter to use a different port than the rbac-proxy will use. From what I could tell the issue was because on this specific node (other nodes did not have this issue at all) both rbac and the node exporter were attaching to port 9100 on the external IP (or maybe internal, can't quite remember). I just changed the node exporter port to prevent the issue altogether.

**Comment by Liyankuan** [comment]
@Dissonant-Tech  sorry，past days，I busy other things.  The cause of my problem is the default namespace already started the same service。 Thanks @Dissonant-Tech

**Comment by akshatgit** [comment]
still getting the same error, even after the above fix. 
node-exporter-62kqs                    1/2     CrashLoopBackOff   6          9m57s
node-exporter-92nl7                    1/2     CrashLoopBackOff   6          9m57s
node-exporter-9d2wl                    1/2     CrashLoopBackOff   6          9m57s
node-exporter-d578t                    1/2     CrashLoopBackOff   6          9m57s
node-exporter-hgdw2                    1/2     CrashLoopBackOff   6          9m57s
node-exporter-lgm2v                    1/2     CrashLoopBackOff   6          9m57s
