### ISSUE TITLE
kube-Prometheus installation failed on K8 initiated with kubeadm, maybe due to problem in prometheus-adapter-apiService.yaml ??

### ISSUE THREAD

**Issue by hshtel** [coreos/prometheus-operator#2211]
**What did you do?**
try to deploy kube-Prometheus on K8 cluster iniated with kubeadm with "kubectl create -f manifests/ || true" with no luck. 

I am not fully aware of how APIservice object work, but is there any relation  between prometheus-adapter-apiService.yaml and metrics-apiservice.yaml which is deployed before with metric-server. or it is another problem.

**What did you expect to see?**
kube-Prometheus installed successfully.

**What did you see instead? Under which circumstances?**
the kube-state-metrics and prometheus-operator pods keep crashing as below, 
```
NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE      NOMINATED NODE   READINESS GATES
monitoring    pod/grafana-6689854d5-7npcp                 1/1     Running   0          86s     10.46.0.3    worker2   <none>           <none>
monitoring    pod/kube-state-metrics-86bc74fd4c-j7c7h     4/4     Error     2          86s     10.40.0.2    master    <none>           <none>
monitoring    pod/node-exporter-6b6d9                     2/2     Running   0          86s     172.1.1.11   worker2   <none>           <none>
monitoring    pod/node-exporter-lfsw8                     2/2     Running   0          86s     172.1.1.9    master    <none>           <none>
monitoring    pod/node-exporter-zzcth                     2/2     Running   0          86s     172.1.1.10   worker1   <none>           <none>
monitoring    pod/prometheus-adapter-5d7cff4b-2gqg9       1/1     Running   0          85s     10.32.0.6    worker1   <none>           <none>
monitoring    pod/prometheus-operator-5cfb7f4c54-kfl4r    1/1     Error     2          90s     10.40.0.1    master    <none>           <none>
```

**Environment**

* Prometheus Operator version:
```
Prometheus Operator version '0.26.0'."
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm.

* Manifests:

```
### prometheus-adapter-apiService.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
```

```
###metrics-apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

```
* Prometheus Operator Logs:

```
root@master:~# kubectl logs pod/prometheus-operator-5cfb7f4c54-kfl4r -n monitoring
ts=2018-12-11T13:27:48.738481288Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
ts=2018-12-11T13:28:18.826524292Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout"

```

**Comment by metalmatze** [comment]
> I am not fully aware of how APIservice object work, but is there any relation between prometheus-adapter-apiService.yaml and metrics-apiservice.yaml which is deployed before with metric-server. or it is another problem.

Yes, there is relation between both. An APIService tells the Kubernetes apiserver which Kubernetes Service (like a normal Service that you deploy with other apps) are responsible for handling requests to that specific API group.
The Prometheus Adapter replaces the metrics server, both implement the same API: `metrics.k8s.io`.
If you want to run the Prometheus Adapter, which you should when also running Prometheus on your cluster, then you can simply remove all traces of the metrics server. Things like `kubectl top` and Horizontal Pod Autoscaler should still work afterwards and be served by Prometheus Adapter from there on.

**Comment by hshtel** [comment]
@metalmatze thanks, I have deleted metric-server but actually the problem still exists. the deployment stops "not all the pods were created" when error occurred on  prometheus-operator,, prometheus-adapter and kube-state-metrics as below:
```
NAME                                   READY   STATUS             RESTARTS   AGE    IP             NODE      NOMINATED NODE   READINESS GATES
grafana-6689854d5-r68gt                1/1     Running            0          7m3s   10.46.0.2      worker2   <none>           <none>
kube-state-metrics-86bc74fd4c-zwwh8    3/4     CrashLoopBackOff   5          7m2s   10.40.0.2      master    <none>           <none>
node-exporter-89ch4                    2/2     Running            0          7m2s   10.205.28.9    master    <none>           <none>
node-exporter-blw5l                    2/2     Running            0          7m2s   10.205.28.11   worker2   <none>           <none>
node-exporter-nkngb                    2/2     Running            0          7m2s   10.205.28.10   worker1   <none>           <none>
prometheus-adapter-7899dcdf87-9hdlf    0/1     CrashLoopBackOff   5          7m1s   10.40.0.3      master    <none>           <none>
prometheus-operator-5cfb7f4c54-x96vf   0/1     CrashLoopBackOff   5          7m4s   10.40.0.1      master    <none>           <none>
```
the current log of prometheus-adapter:
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/prometheus-adapter-7899dcdf87-9hdlf -n monitoring
I1211 18:54:40.597247       1 adapter.go:86] successfully using in-cluster auth
F1211 18:55:10.598081       1 adapter.go:230] unable to install resource metrics API: unable to construct dynamic discovery mapper: unable to populate initial set of REST mappings: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```
the current log of Prometheus Operator:
```

root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/prometheus-operator-5cfb7f4c54-x96vf -n monitoring
ts=2018-12-11T18:54:49.739414344Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
ts=2018-12-11T18:55:19.744455411Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout"
```
the current log of kube-state-metrics
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/kube-state-metrics-86bc74fd4c-zwwh8  -n monitoring -c kube-state-metrics
I1211 18:54:52.729131       1 main.go:76] Using default collectors
I1211 18:54:52.729181       1 main.go:90] Using all namespace
I1211 18:54:52.729187       1 main.go:96] No metric whitelist or blacklist set. No filtering of metrics will be done.
W1211 18:54:52.729201       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1211 18:54:52.731024       1 main.go:145] Testing communication with server
F1211 18:55:22.731429       1 main.go:112] Failed to create client: ERROR communicating with apiserver: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```
just to make sure I am doing everything right, how to ensure that "--authentication-token-webhook=true" and "--authorization-mode=Webhook" is set correctly. and if not how to set these flags in kubeadm cluster.

**Comment by hshtel** [comment]
@metalmatze I have below error when getting the APIservices:
```
NAME                                                                     SERVICE                         AVAILABLE                  AGE
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   False (MissingEndpoints)   9m
```

and below is status from "kubectl get apiservice v1beta1.metrics.k8s.io -o yaml":
```
status:
  conditions:
  - lastTransitionTime: "2018-12-12T07:59:47Z"
    message: endpoints for service/prometheus-adapter in "monitoring" have no addresses
    reason: MissingEndpoints
    status: "False"
    type: Available
```

**Comment by metalmatze** [comment]
What's the output of `kubectl describe svc - n monitoring prometheus-adapter`?

**Comment by hshtel** [comment]
@metalmatze as below dear:
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl describe svc -n monitoring prometheus-adapter
Name:              prometheus-adapter
Namespace:         monitoring
Labels:            name=prometheus-adapter
Annotations:       <none>
Selector:          name=prometheus-adapter
Type:              ClusterIP
IP:                10.96.177.124
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:
Session Affinity:  None
Events:            <none>
```

**Comment by metalmatze** [comment]
Ok. Thanks. What about the Pod?
`kubectl describe pod -n monitoring prometheus-adapter-xxxxx`

**Comment by hshtel** [comment]
@metalmatze 
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl describe pod -n monitoring prometheus-adapter-7899dcdf87-fnvjr
Name:               prometheus-adapter-7899dcdf87-fnvjr
Namespace:          monitoring
Priority:           0
PriorityClassName:  <none>
Node:               master/172.1.1.9
Start Time:         Wed, 12 Dec 2018 04:01:25 -0500
Labels:             name=prometheus-adapter
                    pod-template-hash=7899dcdf87
Annotations:        <none>
Status:             Running
IP:                 10.40.0.2
Controlled By:      ReplicaSet/prometheus-adapter-7899dcdf87
Containers:
  prometheus-adapter:
    Container ID:  docker://12f1f3ddcf41a0f265b3644320d51a5b363b2f57f2ecc8c34f06c17e7e514855
    Image:         quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.0
    Image ID:      docker-pullable://quay.io/coreos/k8s-prometheus-adapter-amd64@sha256:f8659d246cdce34b8771ad8a7d7922f894da3f7b709b6bb556402459cbe8434a
    Port:          6443/TCP
    Host Port:     0/TCP
    Args:
      --cert-dir=/var/run/serving-cert
      --config=/etc/adapter/config.yaml
      --logtostderr=true
      --metrics-relist-interval=1m
      --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
      --secure-port=6443
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 12 Dec 2018 04:10:06 -0500
      Finished:     Wed, 12 Dec 2018 04:10:36 -0500
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /etc/adapter from config (rw)
      /tmp from tmpfs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-adapter-token-5lspn (ro)
      /var/run/serving-cert from volume-serving-cert (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tmpfs:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  volume-serving-cert:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      adapter-config
    Optional:  false
  prometheus-adapter-token-5lspn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-adapter-token-5lspn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned monitoring/prometheus-adapter-7899dcdf87-fnvjr to master
  Normal   Pulled     9m49s (x5 over 13m)   kubelet, master    Container image "quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.0" already present on machine
  Normal   Created    9m49s (x5 over 13m)   kubelet, master    Created container
  Normal   Started    9m49s (x5 over 13m)   kubelet, master    Started container
  Warning  BackOff    3m10s (x31 over 12m)  kubelet, master    Back-off restarting failed container
```

**Comment by metalmatze** [comment]
It seems the Pod is constantly restarting, when looking at the Events of that Pod. In that case, as no Pod is healthy, Kubernetes won't set an Endpoint on the Service.
Can you share the logs of prometheus-adapter? Thanks

**Comment by hshtel** [comment]
this is the prometheus-adapter log:
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs -n monitoring pod/prometheus-adapter-7899dcdf87-fnvjr
I1212 10:34:33.566690       1 adapter.go:86] successfully using in-cluster auth
F1212 10:35:03.567408       1 adapter.go:230] unable to install resource metrics API: unable to construct dynamic discovery mapper: unable to populate initial set of REST mappings: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by s-urbaniak** [comment]
@hshtel when you start a vanilla busybox pod, can you contact the api server by `curl -v -k https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}`? I seems the api server is not accessible from within the cluster.

**Comment by hshtel** [comment]
@s-urbaniak before deploying prometheus, I deployed metric-server and it worked fine, I was able to kubectl top nodes successfully. so I think  the api server is accessible; right.

**Comment by metalmatze** [comment]
If it is not the apiserver I guess that there are some objects left over from the metrics server that conflict with the Prometheus Adapter. Can you double check that you have removed all objects from you cluster which the metrics server created. Additionally please check if you can access the apiserver like @s-urbaniak suggested. :blush:

**Comment by Shini31** [comment]
Hello,

I have exactly the same behavior. I just check if i can access the apiserver:
```
curl -k -v https://10.96.0.1:443/api
*   Trying 10.96.0.1...
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* found 152 certificates in /etc/ssl/certs/ca-certificates.crt
* found 612 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: kube-apiserver (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=kube-apiserver
* 	 start date: Wed, 05 Dec 2018 10:03:37 GMT
* 	 expire date: Thu, 05 Dec 2019 15:11:19 GMT
* 	 issuer: CN=kubernetes
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api HTTP/1.1
> Host: 10.96.0.1
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 13 Dec 2018 09:34:42 GMT
< Content-Length: 182
< 
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "x.x.x.x:6443"
    }
  ]
* Connection #0 to host 10.96.0.1 left intact
```

**Comment by hshtel** [comment]
@s-urbaniak @metalmatze Hello again;
curl is not found from inside the busybox:
```
root@master:~# kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # curl -k -v https://10.96.0.1:443/api
sh: curl: not found
```
I tried wget instead:
```
/ # wget https://10.96.0.1:443/api --no-check-certificate
Connecting to 10.96.0.1:443 (10.96.0.1:443)
api                  100% |*******************************************************************************************************************************************************************|   183  0:00:00 ETA
/ #
```
I tried the curl from grafana pod:
```
root@master:~# kubectl exec -it -n monitoring grafana-6689854d5-r5bn5 -- sh
$ curl -k -v https://10.96.0.1:443/api
*   Trying 10.96.0.1...
* TCP_NODELAY set
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=kube-apiserver
*  start date: Dec  4 13:17:54 2018 GMT
*  expire date: Dec  4 13:17:54 2019 GMT
*  issuer: CN=kubernetes
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56024f8b7dc0)
> GET /api HTTP/1.1
> Host: 10.96.0.1
> User-Agent: curl/7.52.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< content-type: application/json
< content-length: 183
< date: Thu, 13 Dec 2018 13:31:19 GMT
<
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.205.28.9:6443"
    }
  ]
* Curl_http_done: called premature == 0
* Connection #0 to host 10.96.0.1 left intact
```

**Comment by Shini31** [comment]
@hshtel, Your problem is still ongoing or you were able to find a solution?

**Comment by Shini31** [comment]
@s-urbaniak, @metalmatze Do you have any idea about the problem after the returns of @hshtel?

**Comment by Shini31** [comment]
Problem solved for me with a fresh reinstall of the k8s cluster. The issue was from Calico which was badly installed

**Comment by s-urbaniak** [comment]
@Shini31 awesome, good to hear you resolved the issue.
@hshtel please recheck your network setup and/or check on a fresh cluster. If the problem persists also on a fresh cluster, feel free to reopen.

**Comment by hash1024** [comment]
On GCP, tried running this 

`kubectl create -f manifests/`

... and I'm getting this error:
Error from server (AlreadyExists): error when creating "manifests/prometheus-adapter-apiService.yaml": apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io" already exists

Tried removing `metrics-server` but it re-spawns right back. GCP's support says this: "since GKE is managed, the metrics-server cannot be deleted since it will automatically get created again"

> The Prometheus Adapter replaces the metrics server, both implement the same API: `metrics.k8s.io`.
> If you want to run the Prometheus Adapter, which you should when also running Prometheus on your cluster, then you can simply remove all traces of the metrics server. Things like `kubectl top` and Horizontal Pod Autoscaler should still work afterwards and be served by Prometheus Adapter from there on.

**Comment by brancz** [comment]
That's unfortunate, but little we can do if GKE dictates that.

**Comment by Shini31** [comment]
Hello,

I have the same issue on GCP with `metric-server`.  
So what is good practice? Delete all yaml related to `prometheus-adapter`?

Regards.

**Comment by brancz** [comment]
That’s probably your best bet. We should make that part of the jsonnet gke patch probably.

**Comment by Shini31** [comment]
Thanks for the answer. Indeed a specific jsonnet for GKE (as it exists for kubeadm) would be a great move !

**Comment by ajay1206** [comment]
@hshtel @Shini31 Going through the same in AKS v1.18.8. Did a fresh resinstall of the clusters too. Any pointers please?

**Comment by brancz** [comment]
I opened a PR for GKE https://github.com/prometheus-operator/kube-prometheus/pull/821

I don't know the situation with AKS well enough to judge whether the same strategy should be applied.

**Comment by George-T-Serban** [comment]
> Problem solved for me with a fresh reinstall of the k8s cluster. The issue was from Calico which was badly installed

This worked for me.

**Comment by liuhaibo0303** [comment]
I ran into the same problem and it has been solved
Check the configuration of your flannel network plug-in to ensure that the pod network segment configuration is consistent with the k8s cluster POD CIDR
`kubectl get configmap -n kube-system -o yaml kube-flannel-cfg > flannel.yaml
vim  flannel.yaml
net-conf.json: |
    {
      "Network": "10.224.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
kubectl apply -f flannel.yaml
`

If the pod network segment of the flannel is inconsistent with the k8s POD CIDR, it will cause the nat table of the node's iptables to be wrong, and the data inside the pod cannot be correctly forwarded to other nodes.
The core of this problem is that we can access the apiserver address normally outside the node, but if the pod where the apiserver is located is different from the node where the prometheus-operator is located, the problem will be triggered.
-------------------------------------------------------------
问题现象：
1、任意node节点可以访问kubernetes 的svc地址
2、pod内部无法访问kubernetes 的svc地址
3、pod内部可以访问其他svc地址
4、pod内部无法访问除本节点外的宿主机IP地址
原因：
1、kubernetes 的svc地址对应的后端endpoints是apiserver pod所在的宿主机地址，而其他svc对应的endpoint地址是pod IP
2、核心是flannel里面的pod网段配置和k8s集群设置的pod网段不一致，会导致node节点iptables中的nat规则错误，pod数据无法正常转发到其他节点IP(但是跨节点间的pod网络是正常的)
解决：
1、修改flannel插件里面的网段配置，和创建k8s集群时的pod cidr网段保持一致
`kubectl get configmap -n kube-system -o yaml kube-flannel-cfg > flannel.yaml
vim  flannel.yaml
net-conf.json: |
    {
      "Network": "10.224.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
kubectl apply -f flannel.yaml
`

**Comment by liuhaibo0303** [comment]
`ls test`
