### ISSUE TITLE
Unable to obtain kube-controller-manager and kube-scheduler monitoring information

### ISSUE THREAD

**Issue by XiaoMuYi** [coreos/prometheus-operator#2255]
**What did you do?**
I use helm to deploy prometheus-operator to monitor binary kubernetes clusters. However, it is not possible to obtain kube-controller-manager and kube-scheduler component data at present.
![image](https://user-images.githubusercontent.com/34268642/50535404-8f57df00-0b84-11e9-85b9-abc3206df5db.png)

**What did you expect to see?**
I want to know how prometheus-operator monitors kubernetes Masters.

**What did you see instead? Under which circumstances?**
Look at the EP created by prometheus-operator and find that the ENDPOINTS field is <none>.
```
$ kubectl get ep -n kube-system |grep "prometheus-operator*"
prometheus-operator-coredns                   172.20.4.2:9153,172.20.5.4:9153                                         36m
prometheus-operator-kube-controller-manager   <none>                                                                  36m
prometheus-operator-kube-etcd                 172.17.80.26:2379,172.17.80.27:2379,172.17.80.28:2379                   36m
prometheus-operator-kube-scheduler            <none>                                                                  36m
prometheus-operator-kubelet                   172.17.80.26:10255,172.17.80.27:10255,172.17.80.28:10255 + 15 more...   28d
```
Service port listening 0.0.0.0.
```
$ ss -lnpt |egrep "kube-controller|kube-scheduler"
LISTEN     0      2048        :::10251                   :::*                   users:(("kube-scheduler",pid=41235,fd=3))
LISTEN     0      2048        :::10252                   :::*                   users:(("kube-controller",pid=41326,fd=3))
LISTEN     0      2048        :::10257                   :::*                   users:(("kube-controller",pid=41326,fd=5))
```
**Environment**

* Prometheus Operator version:
```
$ grep -A 3 "image:" /data/prometheus-operator-01/values.yaml
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.15.3

--
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.26.0
    pullPolicy: IfNotPresent
--
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.5.0
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
  Binary manual installation

* Manifests:

* Prometheus Operator Logs:

**Comment by okamototk** [comment]
I finally found the resolution. Use 0.0.0.0 for scheduler and contoller-manager bind address. 
Following is kubeadm config example, 

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
...
controllerManager:
  extraArgs:
    address: "0.0.0.0"
scheduler:
  extraArgs:
    address: "0.0.0.0"
```

**Comment by brancz** [comment]
@XiaoMuYi does that solve your issue?

**Comment by XiaoMuYi** [comment]
> @XiaoMuYi does that solve your issue?

Using the latest version has been resolved

**Comment by neoakris** [comment]
https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html
May also be of help, says you need to create services for them to be discovered.

**Comment by retr0h** [comment]
Oddly my kubespray scheduler is running on a different port:

```
jodewey@csg-nscg-0001:~$ ps -ef | grep scheduler
root        2875    2853  0 17:12 ?        00:01:51 kube-scheduler xxxxx
jodewey   461907  458260  0 23:31 pts/0    00:00:00 grep scheduler
jodewey@csg-nscg-0001:~$ sudo lsof -p 2875 | grep TCP
kube-sche 2875 root    5u     IPv6              33254      0t0     TCP *:10259 (LISTEN)
```

**Comment by ksa-real** [comment]
The issue is there still/again. Problems:
- Both `kube-scheduler` and `kube-controller-manager` have 127.0.0.1 as DN in TLS certificate. So scraping from a non-master host is only possible with `insecureSkipVerify: true`.
- By default, both components bind to 127.0.0.1. Binding with `extraArgs: {bind-address: "0.0.0.0"}` works, but exposes the components too broadly: cluster-wide and probably even outside the cluster, depending on bound interfaces. 

Is there a recommended approach to this issue? I see two approaches:
- Design component endpoints with Prometheus scraper in mind: i.e. they provide a certificate that includes master nodes' IPs (similar to etcd). Bind to the main network interface instead of 127.0.0.1. This likely requires support by `kubeadm`.
- Delegate scraping to some collector, ran as a DaemonSet. E.g. node-exporter can act as such. It may pass proxy request to the node and respond to Prometheus with the result.

**Comment by syednadeembe** [comment]
@okamototk @ksa-real 
Can you please state how to use extraArgs: {bind-address: "0.0.0.0"} for controllerManager: and scheduler:

I updated the kubeadm-config comfig map as below but still facing the same issue.
#############################################################
kubectl describe cm kubeadm-config -n kube-system
#############################################################
Name:         kubeadm-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
ClusterConfiguration:
----
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
    cloud-provider: aws
    feature-gates: TTLAfterFinished=true
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    address: "0.0.0.0"
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.19.7
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler:
  extraArgs:
    address: "0.0.0.0"

ClusterStatus:
----
apiEndpoints:
  vmnxkubdvm01.eur.ad.sag:
    advertiseAddress: 10.60.27.248
    bindPort: 6443
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterStatus

Events:  <none>
